CREATE TABLE IF NOT EXISTS Lot (
    LotID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL UNIQUE,
    Latitude REAL NOT NULL DEFAULT '0.0',
    Longitude REAL NOT NULL DEFAULT '0.0',
    Active INTEGER NOT NULL DEFAULT '0'
);
CREATE TABLE IF NOT EXISTS Source (
    SourceID INTEGER PRIMARY KEY,
    URI TEXT NOT NULL UNIQUE,
    Username TEXT NOT NULL,
    Password TEXT NOT NULL,
    Location TEXT NOT NULL,
    Active INTEGER NOT NULL DEFAULT '0'
);
CREATE TABLE IF NOT EXISTS Type (
    TypeID INTEGER PRIMARY KEY,
    Description TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS Zone (
    ZoneID INTEGER NOT NULL,
    LotID INTEGER NOT NULL,
    SourceID INTEGER NOT NULL,
    TypeID INTEGER NOT NULL,
    TotalSpaces INTEGER NOT NULL DEFAULT '0',
    PolyCoords TEXT NOT NULL UNIQUE,
    Active INTEGER NOT NULL DEFAULT '0',
    FOREIGN KEY (LotID)
        REFERENCES Lot (LotID),
    FOREIGN KEY (SourceID)
        REFERENCES Source (SourceID),
    FOREIGN KEY (TypeID)
        REFERENCES Type (TypeID),
	PRIMARY KEY (ZoneID, LotID, SourceID, TypeID)
);
CREATE TABLE IF NOT EXISTS OccupancyLog (
    Timestamp REAL NOT NULL,
    ZoneID INTEGER NOT NULL,
    TypeID INTEGER NOT NULL,
    LotID INTEGER NOT NULL,
    OccupiedSpaces INTEGER NOT NULL DEFAULT '0',
    TotalSpaces INTEGER NOT NULL DEFAULT '0',
    FOREIGN KEY (ZoneID)
        REFERENCES Zone (ZoneID),
    FOREIGN KEY (TypeID)
        REFERENCES Type (TypeID),
    FOREIGN KEY (LotID)
        REFERENCES Lot (LotID),
	PRIMARY KEY (Timestamp, ZoneID, TypeID, LotID)
);
